version: '3.3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'blog_prod'
    volumes:
      - database_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8001:3000"
    environment:
      RAILS_ENV: 'production'
      PG_HOST: db
      PG_PORT: 5432
      PG_DB: 'blog_prod'
      PG_USER: 'root'
      PG_PASS: 'password'
    extra_hosts:
      host.docker.internal: host-gateway

volumes:
  database_data:
    external: true
