version: '3.3'

services:
  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    extra_hosts:
      host.docker.internal: host-gateway