default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["PG_HOST"] || 'localhost' %>
  port: <%= ENV["PG_PORT"] || 5432 %>
  database: <%= ENV["PG_DB"] || blog_dev %>
  username: <%= ENV["PG_USER"] || root %>
  password: <%= ENV["PG_PASS"] || password %>
  pool: 5

development:
  <<: *default
  database: blog_dev

production:
  <<: *default
