default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  database: blog_dev
  username: root
  password: password
  pool: 5

development:
  <<: *default
  database: blog_dev

production:
  <<: *default
